# Generated by Django 4.2.2 on 2023-06-28 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=50)),
                ('prenom_utilisateur', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(default='simple_utilisateur', max_length=30)),
                ('profilePicture', models.ImageField(default='uploads/user/user_placeholder.jpeg', upload_to='uploads/user/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison', models.DateField()),
                ('status_annulation', models.BooleanField()),
                ('date_annulation', models.DateField()),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('date_connexion', models.DateField()),
                ('date_deconnexion', models.DateField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('quantite_stock', models.IntegerField()),
                ('seuil_minimal', models.IntegerField()),
                ('categorie', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('prix', models.IntegerField()),
                ('pathImg', models.ImageField(default='uploads/products/logo.png', upload_to='uploads/products/')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id_payement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id_panier', models.AutoField(primary_key=True, serialize=False)),
                ('produits', models.ManyToManyField(blank=True, to='ecommerce_api.produit')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('date_notification', models.DateField()),
                ('message', models.CharField(max_length=100)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id_livraison', models.AutoField(primary_key=True, serialize=False)),
                ('lieu', models.CharField(max_length=100)),
                ('id_commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(blank=True, to='ecommerce_api.produit'),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.AutoField(primary_key=True, serialize=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
