# Generated by Django 4.2.2 on 2023-06-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.IntegerField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField()),
                ('date_livraison', models.DateField()),
                ('status_annulation', models.BooleanField()),
                ('date_annulation', models.DateField()),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('quantite_stock', models.IntegerField()),
                ('seuil_minimal', models.IntegerField()),
                ('categorie', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=50)),
                ('prenom_utilisateur', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('date_connexion', models.DateField()),
                ('date_deconnexion', models.DateField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id_payement', models.IntegerField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id_panier', models.IntegerField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('produits', models.ManyToManyField(to='ecommerce_api.produit')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.IntegerField(primary_key=True, serialize=False)),
                ('date_notification', models.DateField()),
                ('message', models.CharField(max_length=100)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id_livraison', models.IntegerField(primary_key=True, serialize=False)),
                ('lieu', models.CharField(max_length=100)),
                ('id_commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.IntegerField(primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.utilisateur')),
                ('produits', models.ManyToManyField(to='ecommerce_api.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.utilisateur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='ecommerce_api.produit'),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.IntegerField(primary_key=True, serialize=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.commande')),
            ],
        ),
    ]
