# Generated by Django 4.2.2 on 2023-06-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0002_remove_evaluation_commentaire_detailcommande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='produit',
            new_name='produits',
        ),
    ]
