# Generated by Django 4.2.2 on 2023-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0002_utilisateur_role_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pathImg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
