# Generated by Django 4.2.2 on 2023-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_rename_produit_commande_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_annulation',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True),
        ),
    ]
