# Generated by Django 4.2.2 on 2023-06-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_produit_pathimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='id_utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.utilisateur'),
        ),
    ]
