# Generated by Django 4.2.2 on 2023-06-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0005_remove_produit_id_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(null=True, to='ecommerce_api.produit'),
        ),
    ]
