# Generated by Django 4.2.2 on 2023-06-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0009_produit_description_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
