# Generated by Django 4.2.2 on 2023-06-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0011_utilisateur_groups_utilisateur_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='id_utilisateur',
            new_name='id',
        ),
    ]
