# Generated by Django 4.2.2 on 2023-06-21 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0012_rename_id_utilisateur_utilisateur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='id_utilisateur',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
